url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Jinghua Ou (歐靜樺)" # the name of your site, e.g. ACME Corp.
description: "Hello, I'm a psycholinguist."
